import type { Models } from "appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts /home/pedroaal/portfolio`.

export type About = Models.Row & {
	name: string;
	title: string;
	phone: string;
	location: string;
	description: string;
	short: string;
	mail: string;
	image: string;
};
