export const DATABASE_ID =
	import.meta.env.VITE_APPWRITE_DATABASE_ID || "public";

export const TABLES = {
	ACCOUNTING_BOOKS: "accounting-books",
	ACTIVITIES: "activities",
	AREAS: "areas",
	ATTENDANCE: "attendance",
	BANK_ACCOUNTS: "bank-accounts",
	BILLING_COMPANIES: "billing-companies",
	BOOK_REFERENCES: "book-references",
	BOOK_TRANSACTIONS: "book-transactions",
	CATEGORIES: "categories",
	CLIENT_COMPANIES: "client-companies",
	CLIENT_FOLLOWERS: "client-followers",
	CLIENTS: "clients",
	COMMENTS: "comments",
	COMPANIES: "companies",
	COMPANY_DETAILS: "company-details",
	CONTACTS: "contacts",
	COST_CENTERS: "cost-centers",
	CREDENTIALS: "credentials",
	CRM: "crm",
	EQUIPMENT: "equipment",
	INKS: "inks",
	INVOICE_ORDERS: "invoice-orders",
	INVOICE_PRODUCTS: "invoice-products",
	INVOICES: "invoices",
	MATERIAL_REQUESTS: "material-requests",
	MATERIALS: "materials",
	MODULES: "modules",
	NOTIFICATIONS: "notifications",
	ORDER_INKS: "order-inks",
	ORDER_PROCESSES: "order-processes",
	ORDERS: "orders",
	PAYMENTS: "payments",
	PAYROLL: "payroll",
	PAYROLL_DOCUMENTS: "payroll-documents",
	PAYROLL_EDUCATION: "payroll-education",
	PAYROLL_FAMILY: "payroll-family",
	PAYROLL_REFERENCES: "payroll-references",
	PROCESSES: "processes",
	PRODUCT_CATEGORIES: "product-categories",
	PRODUCTION_RESETS: "production-resets",
	PRODUCTS: "products",
	PROFILE_MODULES: "profile-modules",
	PROFILES: "profiles",
	ROLES: "roles",
	SCHEDULES: "schedules",
	SUPPLIERS: "suppliers",
	TAXES: "taxes",
	USER_BOOK: "user-book",
	USER_PROCESSES: "user-processes",
	USERS: "users",
	WITHHOLDINGS: "withholdings",
};
